// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJE4ZLbK5atOJRVs8jYd214Yx2BC7vPxU',
    appId: '1:115866839967:web:2135970ace6018eb2f2baa',
    messagingSenderId: '115866839967',
    projectId: 'rdp-todolist-53125',
    authDomain: 'rdp-todolist-53125.firebaseapp.com',
    storageBucket: 'rdp-todolist-53125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrFZ6kJS2JVlx_dWuXiJplUwZapUaxJ4',
    appId: '1:115866839967:android:0f9b893d6daec32e2f2baa',
    messagingSenderId: '115866839967',
    projectId: 'rdp-todolist-53125',
    storageBucket: 'rdp-todolist-53125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZUPzQmRsg870DKVVoRfBO0IYjrHf9ok',
    appId: '1:115866839967:ios:9a62730cc12488842f2baa',
    messagingSenderId: '115866839967',
    projectId: 'rdp-todolist-53125',
    storageBucket: 'rdp-todolist-53125.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZUPzQmRsg870DKVVoRfBO0IYjrHf9ok',
    appId: '1:115866839967:ios:9a62730cc12488842f2baa',
    messagingSenderId: '115866839967',
    projectId: 'rdp-todolist-53125',
    storageBucket: 'rdp-todolist-53125.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJE4ZLbK5atOJRVs8jYd214Yx2BC7vPxU',
    appId: '1:115866839967:web:47cfae5664ae78742f2baa',
    messagingSenderId: '115866839967',
    projectId: 'rdp-todolist-53125',
    authDomain: 'rdp-todolist-53125.firebaseapp.com',
    storageBucket: 'rdp-todolist-53125.firebasestorage.app',
  );
}
